language: node_js
node_js:
  - "7"
dist: trusty # needs Ubuntu Trusty
sudo: true  # needed for Chromium sandbox
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
script:
  - yarn run travis
notifications:
  webhooks: https://greenlight.operationspark.org/api/v2/webhooks/travisci
